lab_5/lab_5/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('form/', include('schedulelist.urls')),
]

lab_5/schedulelist/urls.py
from django.urls import re_path
from .views import submit
from .views import show

app_name = "sched"
urlpatterns = [
    # re_path(r'^nothing/', views.nothing, name="nothing"),
    re_path(r'^', submit, name="submit"),
    re_path(r'show',show, name="show"),
]

lab_5/schedulelist/models.py
from django.db import models


class data(models.Model):
    hari = models.CharField(max_length=27)
    waktu = models.DateField(null=True)
    nama_kegiatan = models.CharField(max_length=27)
    kategori = models.CharField(max_length=27)

lab_5/schedulelist/forms.py
from django import forms
from .models import data

class schedule_form(forms.Form):
    model = data
    fields = ['hari','waktu','nama_kegiatan','kategori']

    hari = forms.CharField(label='hari', required=True, max_length=27)
    waktu = forms.DateField(required=True)
    nama_kegiatan = forms.CharField(required=True)
    kategori = forms.CharField(required=True)

lab_5/schedulelist/templates/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }
    
    hari = forms.CharField(label='hari', required=True, max_length=27, widget=forms.TextInput(attrs=attrs))
    tanggaldanjam = forms.DateTimeField(required=True, widget=forms.TextInput(attrs=attrs))
    nama_kegiatan = forms.CharField(widget=forms.TextInput(attrs=attrs), required=True)
    kategori = forms.CharField(widget=forms.TextInput(attrs=attrs), required=True)

lab_5/schedulelist/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from .forms import schedule_form
from .models import data
def submit(request):
	form = schedule_form(request.POST)
	if request.method == 'POST':
		if form.is_valid():
			response = {}
			response['hari'] = form.cleaned_data.get('hari')
			response['waktu'] = form.cleaned_data.get('waktu')
			response['nama_kegiatan'] = form.cleaned_data.get('nama_kegiatan')
			response['kategori'] = form.cleaned_data.get('kategori')
			yang_mau_disave = data(
				hari = response['hari'],
				waktu =response['waktu'],
				nama_kegiatan =response['nama_kegiatan'],
				kategori =response['kategori'])
			yang_mau_disave.save()
			return render(request,'index.html',{'response':response})
	else :
		form = schedule_form()
		return render(request,'index.html', {'schedule_form' : form})
	return HttpResponseRedirect('show')

def show(request):
	schedule = data.objects.all()
	return render(request,'show.html',{'schedule' : schedule})

lab_5/schedulelist/templates/index.html
<html>
	<head></head>
	<body>
		<section name="form">
        <h2>Add Schedule</h2>
        <form id="form" method="POST" action="{% url 'sched:submit' %}">
            {% csrf_token %}
            {{ schedule_form.as_p }}
            <br>
            <button type="submit" style="padding:15px 32px;text-align: center;" value="Submit">Submit</button><br>
            <button type="submit" style="padding:15px 32px;text-align: center;" formaction="show" value="Show">Show</button>
        </form>
    	</section>


	</body>
</html>

lab_5/schedulelist/templates/show.html
<html>
	<head></head>
	<body>
		<div class = "container">
            <div class="row" style="margin: 20%; position: absolute; left: 15%;">
                <table class ="table">
                    <thead>
                        <th>Hari</th>
                        <th>Tanggal</th>
                        <th>Nama</th>
                        <th>Kategori</th>
                    </thead>
                    <tbody>
                        {% for i in schedule %}
                        <tr>
                            <td>{{i.hari}}</td>
                            <td>{{i.waktu}}</td>
                            <td>{{i.nama_kegiatan}}</td>
                            <td>{{i.kategori}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
	</body>
</html>